language: python
install: pip install -r requirements.txt
script:
  - pytest
  - python setup.py sdist bdist_wheel

branches:
  only:
  - master
  - /\d+\.\d+\.\d+/

deploy:
  - provider: releases
    api_key: '$GITHUB_API_KEY'
    skip_cleanup: true
    file_glob: true
    file: "dist/**/*"
    on:
      tags: true

